const express = require('express');
const router = express.Router();
//Import middleware and controllers
const { mid} = require('../backend/middleware/mwd')
const { isAdmin, isCustomer, authenticateToken } = require('../backend/middleware/auth')
const { login, logout } = require('../backend/controllers/login')
const { home, about, details } = require('../backend/controllers/users')
const { resetPassword } = require('../backend/controllers/resetPassword')
const { insertCus } = require('../backend/controllers/customer-controller')
const { insertProduct, getAllProducts, getProductById, updateProductById, deleteProduct, getProductByCategory, getProductBySubCategory } = require('../backend/controllers/product-controller')
const { productSearch } = require('../backend/controllers/product-search')
const { createOrder, viewOrders, viewParticularOrder, updateOrder, cancelOrder, updateOrderStatus, calcOrderTotal, convertCartToOrder } = require('../backend/controllers/order-controller')
const { addToCart, checkOut, retrieveCart, cleanUpOldCarts } = require('../backend/controllers/cart-controller')
// Define routes
// router.get('/', home)
router.post('/login', mid, login)
router.post('/logout', logout)
router.post('/register', insertCus)
router.post('/products', insertProduct)
router.get('/products', getAllProducts)
router.get('/products/:category', getProductByCategory);
router.get('/products/:category/:subcategory', getProductBySubCategory)
router.get('/products/:Productid', getProductById)
router.put('/products/:Productid', updateProductById)
router.delete('products/:Productid', deleteProduct)
router.post('/createorder', createOrder)
router.get('/vieworders', viewOrders)
router.get('/orders/:orderId', viewParticularOrder)
router.put('/orders/:orderId', updateOrder)
router.put('/orders/:orderId/status', updateOrderStatus)
router.delete('/orders/:orderId', cancelOrder)
router.get('/orders/:orderId/calculateTotal', calcOrderTotal)
router.put('/insertintocart', addToCart)
router.delete('/checkout', checkOut)
router.post('/retrievecart', retrieveCart)
router.delete('/cleanup', cleanUpOldCarts)
router.post('/convertcarttoorder', convertCartToOrder)
router.get('/admin/dashboard', isAdmin, (req, res) => {
    res.json({ message: 'Admin dashboard accessed successfully' })
})
router.get('/customer/profile', isCustomer, (req, res) => {
    res.json({ message: 'Customer profile accessed successfully' })
})
// router.get('/details', verifyAuth, details)
router.get('/reset', resetPassword)
module.exports = { router };